### ISSUE TITLE
{params}

### ISSUE THREAD

**Issue by donutcake1** [blargbot/VSCode-BBTag#3]
When using `{params}`, it counts it as error, when normally it should be same as `{args}`
~~Not important though, but if you fix it, it'll be cool~~

**Comment by donutcake1** [comment]
Update:
It displays an 

> Unknown SubTag: params

 in output.

**Comment by danny-may** [comment]
The latest version of the codebase now pulls all subtag info from blargbot.xyz, which includes the params/paramsarray/paramslength subtags, so this should be fixed once the new version of the extension goes live!
